### ISSUE TITLE
Installation fail on updating submodule

### ISSUE THREAD

**Issue by allanj** [sivareddyg/UDepLambda#8]
I try to build it following the installation guided.
But seems I can not update the lib submodule

`
Admins-MacBook-Air:UDepLambda 1001981$ git submodule update --init --recursive lib
`
`
Cloning into '/Users/allanjie/Documents/workspace/UDepLambda/lib'...
`
`
Permission denied (publickey).
`
`
fatal: Could not read from remote repository.
`
`
Please make sure you have the correct access rights
`
`
and the repository exists.
`
`
fatal: clone of 'git@bitbucket.org:sivareddyg/udeplambda-lib.git' into submodule path 
`
`
'/Users/allanjie/Documents/workspace/UDepLambda/lib' failed
`
`
Failed to clone 'lib'. Retry scheduled
`
`
Cloning into '/Users/allanjie/Documents/workspace/UDepLambda/lib'...
`
`
Warning: Permanently added the RSA host key for IP address '104.192.143.2' to the list of known hosts.
`
`
Permission denied (publickey).
`
`
fatal: Could not read from remote repository.
`

`
Please make sure you have the correct access rights
`
`
and the repository exists.
`
`
fatal: clone of 'git@bitbucket.org:sivareddyg/udeplambda-lib.git' into submodule path 
`
`
'/Users/allanjie/Documents/workspace/UDepLambda/lib' failed
`
`
Failed to clone 'lib' a second time, aborting
`
`
Admins-MacBook-Air:UDepLambda 1001981$ 
`

**Comment by sivareddyg** [comment]
Thanks @allanj. I pushed a [fix](https://github.com/sivareddyg/UDepLambda/commit/f7c3f202d99bfd5bdd9fc38b81451f5de4e68a8b) now. 

Can you verify if this is working now. Just pull the recent commit and try the steps again. Please close the issue if this is resolved.

**Comment by allanj** [comment]
I just pull and see the changed in .gitmodule file. But it is still showing the same error.

**Comment by sivareddyg** [comment]
My bad, the required repo was private. I made it public.

Some Troubleshooting:

If you get this error
```
(gnome-ssh-askpass:6221): Gtk-WARNING **: cannot open display:
Clone of 'https://sivareddyg@bitbucket.org/sivareddyg/udeplambda-lib.git' into submodule path 'lib' failed
```
try using this command:

    unset SSH_ASKPASS

If it asks for password use empty password. Some machines may give this error after entering empty password. Ignore it. You will have required files downloaded.
```
error: pathspec 'lib_data/ud-models-v1.3' did not match any file(s) known to git.
```

Any luck?

**Comment by hvhvhh** [comment]
@sivareddyg : thanks for your response. But I still got an error of accessing your repo.

`Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@bitbucket.org:sivareddyg/webquestions.git' into submodule path 'data/WebQuestions' failed`

**Comment by sivareddyg** [comment]
@hvhvhh I think you are either using 

    git submodule update --init --recursive

or 

    git submodule update --init --recursive data/WebQuestions

Instead please download the modules you require. What command did you use?

WebQuestions in multiple languages is not released yet for public use. I am waiting for permission from Google. Please wait on this.

**Comment by hvhvhh** [comment]
@sivareddyg : thank you for you reply. It is a small error on my local file. Your new code is okay now and I can get fully your libs.

P/s: thanks for your information of WebQuestions. :+1:

**Comment by allanj** [comment]
@sivareddyg I restarted the whole installation from `git clone` and it works now (BUILD SUCCESSFUL).
